import type { Node, SandstoneCore } from '..'

export type ResourceClassArguments = {
  /**
   * Whether the associated Node should be added to Sandstone Core.
   *
   * @default true
   */
  addToSandstoneCore?: boolean

  /**
   * Whether the MCFunction has been created explicitely by a user, or automatically generated by Sandstone.
   *
   * @default 'sandstone'
   */
  creator?: 'user' | 'sandstone'
}

export type ResourceNode<T = ResourceClass<any>> = Node & {
  resource: T
}

type ResourceNodeConstructor<N extends Node> = new (sandstoneCore: SandstoneCore, resource: any) => N

export abstract class ResourceClass<N extends ResourceNode = ResourceNode<any>> {
  protected generated: boolean

  protected node: N

  protected creator: NonNullable<ResourceClassArguments['creator']>

  constructor(sandstoneCore: SandstoneCore, NodeType: ResourceNodeConstructor<N>, public name: string, args: ResourceClassArguments = {}) {
    this.node = new NodeType(sandstoneCore, this)

    if (args.addToSandstoneCore) {
      sandstoneCore.resourceNodes.add(this.node)
    }

    this.generated = false
    this.creator = args.creator ?? 'sandstone'
  }

  generate = () => {
    this.generated = true
  }

  toString(): string {
    return this.name
  }
}
