/* eslint-disable */
/** Auto-generated by jsonToTS.ts - Represents the types expected for each argument nodes. */

import { ParsersMap } from './parsersMap'

type ParsersIdMapObject<returnType, rootNode> = ({
  0:
    ((targets: ParsersMap['minecraft:entity']) => rootNode)
  1:
    ((advancement: ParsersMap['minecraft:resource_location']) => rootNode)
  2:
    ((advancement: ParsersMap['minecraft:resource_location']) => returnType) &
    ((advancement: ParsersMap['minecraft:resource_location'], criterion: ParsersMap['brigadier:string']) => rootNode)
  3:
    ((target: ParsersMap['minecraft:entity'], attribute: ParsersMap['minecraft:resource_location']) => rootNode)
  4:
    ((scale: ParsersMap['brigadier:double']) => rootNode)
  5:
    ((value: ParsersMap['brigadier:double']) => rootNode)
  6:
    ((uuid: ParsersMap['minecraft:uuid'], name: ParsersMap['brigadier:string'], value: ParsersMap['brigadier:double']) => rootNode)
  7:
    ((uuid: ParsersMap['minecraft:uuid']) => rootNode)
  8:
    ((get: ParsersMap['undefined'], uuid: ParsersMap['minecraft:uuid']) => returnType) &
    ((get: ParsersMap['undefined'], uuid: ParsersMap['minecraft:uuid'], scale: ParsersMap['brigadier:double']) => rootNode)
  9:
    ((targets: ParsersMap['minecraft:game_profile']) => returnType) &
    ((targets: ParsersMap['minecraft:game_profile'], reason: ParsersMap['minecraft:message']) => rootNode)
  10:
    ((target: ParsersMap['brigadier:string']) => returnType) &
    ((target: ParsersMap['brigadier:string'], reason: ParsersMap['minecraft:message']) => rootNode)
  11:
    ((id: ParsersMap['minecraft:resource_location'], name: ParsersMap['minecraft:component']) => rootNode)
  12:
    ((id: ParsersMap['minecraft:resource_location']) => rootNode)
  13:
    ((max: ParsersMap['brigadier:integer']) => rootNode)
  14:
    ((name: ParsersMap['minecraft:component']) => rootNode)
  15:
    ((value: ParsersMap['brigadier:integer']) => rootNode)
  16:
    ((visible: ParsersMap['brigadier:bool']) => rootNode)
  17:
    ((targets: ParsersMap['minecraft:entity']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], item: ParsersMap['minecraft:item_predicate']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], item: ParsersMap['minecraft:item_predicate'], maxCount: ParsersMap['brigadier:integer']) => rootNode)
  18:
    ((begin: ParsersMap['minecraft:block_pos'], end: ParsersMap['minecraft:block_pos'], destination: ParsersMap['minecraft:block_pos']) => rootNode)
  19:
    ((filter: ParsersMap['minecraft:block_predicate']) => rootNode)
  20:
    ((targetPos: ParsersMap['minecraft:block_pos']) => returnType) &
    ((targetPos: ParsersMap['minecraft:block_pos'], path: ParsersMap['minecraft:nbt_path']) => returnType) &
    ((targetPos: ParsersMap['minecraft:block_pos'], path: ParsersMap['minecraft:nbt_path'], scale: ParsersMap['brigadier:double']) => rootNode)
  21:
    ((target: ParsersMap['minecraft:entity']) => returnType) &
    ((target: ParsersMap['minecraft:entity'], path: ParsersMap['minecraft:nbt_path']) => returnType) &
    ((target: ParsersMap['minecraft:entity'], path: ParsersMap['minecraft:nbt_path'], scale: ParsersMap['brigadier:double']) => rootNode)
  22:
    ((target: ParsersMap['minecraft:resource_location']) => returnType) &
    ((target: ParsersMap['minecraft:resource_location'], path: ParsersMap['minecraft:nbt_path']) => returnType) &
    ((target: ParsersMap['minecraft:resource_location'], path: ParsersMap['minecraft:nbt_path'], scale: ParsersMap['brigadier:double']) => rootNode)
  23:
    ((targetPos: ParsersMap['minecraft:block_pos'], nbt: ParsersMap['minecraft:nbt_compound_tag']) => rootNode)
  24:
    ((target: ParsersMap['minecraft:entity'], nbt: ParsersMap['minecraft:nbt_compound_tag']) => rootNode)
  25:
    ((target: ParsersMap['minecraft:resource_location'], nbt: ParsersMap['minecraft:nbt_compound_tag']) => rootNode)
  26:
    ((targetPos: ParsersMap['minecraft:block_pos'], targetPath: ParsersMap['minecraft:nbt_path']) => rootNode)
  27:
    ((sourcePos: ParsersMap['minecraft:block_pos']) => returnType) &
    ((sourcePos: ParsersMap['minecraft:block_pos'], sourcePath: ParsersMap['minecraft:nbt_path']) => rootNode)
  28:
    ((source: ParsersMap['minecraft:entity']) => returnType) &
    ((source: ParsersMap['minecraft:entity'], sourcePath: ParsersMap['minecraft:nbt_path']) => rootNode)
  29:
    ((source: ParsersMap['minecraft:resource_location']) => returnType) &
    ((source: ParsersMap['minecraft:resource_location'], sourcePath: ParsersMap['minecraft:nbt_path']) => rootNode)
  30:
    ((value: ParsersMap['minecraft:nbt_tag']) => rootNode)
  31:
    ((index: ParsersMap['brigadier:integer']) => rootNode)
  32:
    ((target: ParsersMap['minecraft:entity'], targetPath: ParsersMap['minecraft:nbt_path']) => rootNode)
  33:
    ((target: ParsersMap['minecraft:resource_location'], targetPath: ParsersMap['minecraft:nbt_path']) => rootNode)
  34:
    ((targetPos: ParsersMap['minecraft:block_pos'], path: ParsersMap['minecraft:nbt_path']) => rootNode)
  35:
    ((target: ParsersMap['minecraft:entity'], path: ParsersMap['minecraft:nbt_path']) => rootNode)
  36:
    ((target: ParsersMap['minecraft:resource_location'], path: ParsersMap['minecraft:nbt_path']) => rootNode)
  37:
    ((name: ParsersMap['brigadier:string']) => rootNode)
  38:
    ((existing: ParsersMap['brigadier:string']) => rootNode)
  39:
    ((targets: ParsersMap['minecraft:game_profile']) => rootNode)
  40:
    ((targets: ParsersMap['minecraft:entity']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], effect: ParsersMap['minecraft:mob_effect']) => rootNode)
  41:
    ((targets: ParsersMap['minecraft:entity'], effect: ParsersMap['minecraft:mob_effect']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], effect: ParsersMap['minecraft:mob_effect'], seconds: ParsersMap['brigadier:integer']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], effect: ParsersMap['minecraft:mob_effect'], seconds: ParsersMap['brigadier:integer'], amplifier: ParsersMap['brigadier:integer']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], effect: ParsersMap['minecraft:mob_effect'], seconds: ParsersMap['brigadier:integer'], amplifier: ParsersMap['brigadier:integer'], hideParticles: ParsersMap['brigadier:bool']) => rootNode)
  42:
    ((targets: ParsersMap['minecraft:entity'], enchantment: ParsersMap['minecraft:item_enchantment']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], enchantment: ParsersMap['minecraft:item_enchantment'], level: ParsersMap['brigadier:integer']) => rootNode)
  43:
    ((axes: ParsersMap['minecraft:swizzle']) => rootNode)
  44:
    ((anchor: ParsersMap['minecraft:entity_anchor']) => rootNode)
  45:
    ((targets: ParsersMap['minecraft:entity'], anchor: ParsersMap['minecraft:entity_anchor']) => rootNode)
  46:
    ((pos: ParsersMap['minecraft:vec3']) => rootNode)
  47:
    ((pos: ParsersMap['minecraft:block_pos'], block: ParsersMap['minecraft:block_predicate']) => rootNode)
  48:
    ((start: ParsersMap['minecraft:block_pos'], end: ParsersMap['minecraft:block_pos'], destination: ParsersMap['minecraft:block_pos']) => rootNode)
  49:
    ((sourcePos: ParsersMap['minecraft:block_pos'], path: ParsersMap['minecraft:nbt_path']) => rootNode)
  50:
    ((source: ParsersMap['minecraft:entity'], path: ParsersMap['minecraft:nbt_path']) => rootNode)
  51:
    ((source: ParsersMap['minecraft:resource_location'], path: ParsersMap['minecraft:nbt_path']) => rootNode)
  52:
    ((entities: ParsersMap['minecraft:entity']) => rootNode)
  53:
    ((predicate: ParsersMap['minecraft:resource_location']) => rootNode)
  54:
    ((target: ParsersMap['minecraft:score_holder'], targetObjective: ParsersMap['minecraft:objective']) => rootNode)
  55:
    ((source: ParsersMap['minecraft:score_holder'], sourceObjective: ParsersMap['minecraft:objective']) => rootNode)
  56:
    ((range: ParsersMap['minecraft:int_range']) => rootNode)
  57:
    ((dimension: ParsersMap['minecraft:dimension']) => rootNode)
  58:
    ((rot: ParsersMap['minecraft:rotation']) => rootNode)
  59:
    ((targets: ParsersMap['minecraft:score_holder'], objective: ParsersMap['minecraft:objective']) => rootNode)
  60:
    ((callback: ParsersMap['sandstone:callback']) => rootNode)
  61:
    ((targets: ParsersMap['minecraft:entity'], amount: ParsersMap['brigadier:integer']) => rootNode)
  62:
    ((from: ParsersMap['minecraft:block_pos'], to: ParsersMap['minecraft:block_pos'], block: ParsersMap['minecraft:block_state']) => rootNode)
  63:
    ((from: ParsersMap['minecraft:column_pos']) => returnType) &
    ((from: ParsersMap['minecraft:column_pos'], to: ParsersMap['minecraft:column_pos']) => rootNode)
  64:
    ((pos: ParsersMap['minecraft:column_pos']) => rootNode)
  65:
    ((from: ParsersMap['minecraft:column_pos']) => rootNode)
  66:
    ((to: ParsersMap['minecraft:column_pos']) => rootNode)
  67:
    ((name: ParsersMap['minecraft:function']) => rootNode)
  68:
    ((target: ParsersMap['minecraft:entity']) => rootNode)
  69:
    ((value: ParsersMap['brigadier:bool']) => rootNode)
  70:
    ((targets: ParsersMap['minecraft:entity'], item: ParsersMap['minecraft:item_stack']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], item: ParsersMap['minecraft:item_stack'], count: ParsersMap['brigadier:integer']) => rootNode)
  71:
    ((command: ParsersMap['brigadier:string']) => rootNode)
  72:
    ((targets: ParsersMap['minecraft:entity']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], reason: ParsersMap['minecraft:message']) => rootNode)
  73:
    ((biome: ParsersMap['sandstone:biome']) => rootNode)
  74:
    ((players: ParsersMap['minecraft:entity']) => rootNode)
  75:
    ((loot_table: ParsersMap['minecraft:resource_location'], pos: ParsersMap['minecraft:block_pos']) => rootNode)
  76:
    ((tool: ParsersMap['minecraft:item_stack']) => rootNode)
  77:
    ((loot_table: ParsersMap['minecraft:resource_location']) => rootNode)
  78:
    ((pos: ParsersMap['minecraft:block_pos']) => rootNode)
  79:
    ((targetPos: ParsersMap['minecraft:block_pos']) => rootNode)
  80:
    ((targetPos: ParsersMap['minecraft:block_pos'], slot: ParsersMap['minecraft:item_slot']) => rootNode)
  81:
    ((count: ParsersMap['brigadier:integer']) => rootNode)
  82:
    ((entities: ParsersMap['minecraft:entity'], slot: ParsersMap['minecraft:item_slot']) => rootNode)
  83:
    ((targetPos: ParsersMap['minecraft:vec3']) => rootNode)
  84:
    ((action: ParsersMap['brigadier:string']) => rootNode)
  85:
    ((targets: ParsersMap['minecraft:entity'], message: ParsersMap['minecraft:message']) => rootNode)
  86:
    ((target: ParsersMap['brigadier:string']) => rootNode)
  87:
    ((name: ParsersMap['minecraft:particle']) => returnType) &
    ((name: ParsersMap['minecraft:particle'], pos: ParsersMap['minecraft:vec3']) => returnType) &
    ((name: ParsersMap['minecraft:particle'], pos: ParsersMap['minecraft:vec3'], delta: ParsersMap['minecraft:vec3'], speed: ParsersMap['brigadier:float'], count: ParsersMap['brigadier:integer']) => rootNode)
  88:
    ((viewers: ParsersMap['minecraft:entity']) => rootNode)
  89:
    ((sound: ParsersMap['sandstone:sound']) => rootNode)
  90:
    ((targets: ParsersMap['minecraft:entity']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], pos: ParsersMap['minecraft:vec3']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], pos: ParsersMap['minecraft:vec3'], volume: ParsersMap['brigadier:float']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], pos: ParsersMap['minecraft:vec3'], volume: ParsersMap['brigadier:float'], pitch: ParsersMap['brigadier:float']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], pos: ParsersMap['minecraft:vec3'], volume: ParsersMap['brigadier:float'], pitch: ParsersMap['brigadier:float'], minVolume: ParsersMap['brigadier:float']) => rootNode)
  91:
    ((port: ParsersMap['brigadier:integer']) => rootNode)
  92:
    ((recipe: ParsersMap['minecraft:resource_location']) => rootNode)
  93:
    ((pos: ParsersMap['minecraft:block_pos'], slot: ParsersMap['minecraft:item_slot'], item: ParsersMap['minecraft:item_stack']) => returnType) &
    ((pos: ParsersMap['minecraft:block_pos'], slot: ParsersMap['minecraft:item_slot'], item: ParsersMap['minecraft:item_stack'], count: ParsersMap['brigadier:integer']) => rootNode)
  94:
    ((targets: ParsersMap['minecraft:entity'], slot: ParsersMap['minecraft:item_slot'], item: ParsersMap['minecraft:item_stack']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], slot: ParsersMap['minecraft:item_slot'], item: ParsersMap['minecraft:item_stack'], count: ParsersMap['brigadier:integer']) => rootNode)
  95:
    ((message: ParsersMap['minecraft:message']) => rootNode)
  96:
    ((function_: ParsersMap['brigadier:string']) => rootNode)
  97:
    ((function_: ParsersMap['minecraft:function'], time: ParsersMap['minecraft:time']) => rootNode)
  98:
    ((objective: ParsersMap['brigadier:string'], criteria: ParsersMap['minecraft:objective_criteria']) => returnType) &
    ((objective: ParsersMap['brigadier:string'], criteria: ParsersMap['minecraft:objective_criteria'], displayName: ParsersMap['minecraft:component']) => rootNode)
  99:
    ((objective: ParsersMap['minecraft:objective']) => rootNode)
  100:
    ((displayName: ParsersMap['minecraft:component']) => rootNode)
  101:
    ((slot: ParsersMap['minecraft:scoreboard_slot']) => returnType) &
    ((slot: ParsersMap['minecraft:scoreboard_slot'], objective: ParsersMap['minecraft:objective']) => rootNode)
  102:
    ((targets: ParsersMap['minecraft:score_holder'], objective: ParsersMap['minecraft:objective'], score: ParsersMap['brigadier:integer']) => rootNode)
  103:
    ((target: ParsersMap['minecraft:score_holder'], objective: ParsersMap['minecraft:objective']) => rootNode)
  104:
    ((target: ParsersMap['minecraft:score_holder']) => rootNode)
  105:
    ((targets: ParsersMap['minecraft:score_holder'], targetObjective: ParsersMap['minecraft:objective'], operation: ParsersMap['minecraft:operation'], source: ParsersMap['minecraft:score_holder'], sourceObjective: ParsersMap['minecraft:objective']) => rootNode)
  106:
    ((targets: ParsersMap['minecraft:score_holder']) => returnType) &
    ((targets: ParsersMap['minecraft:score_holder'], objective: ParsersMap['minecraft:objective']) => rootNode)
  107:
    ((pos: ParsersMap['minecraft:block_pos'], block: ParsersMap['minecraft:block_state']) => rootNode)
  108:
    ((minutes: ParsersMap['brigadier:integer']) => rootNode)
  109:
    ((targets: ParsersMap['minecraft:entity']) => returnType) &
    ((targets: ParsersMap['minecraft:entity'], pos: ParsersMap['minecraft:block_pos']) => rootNode)
  110:
    ((target: ParsersMap['minecraft:entity']) => returnType) &
    ((target: ParsersMap['minecraft:entity'], player: ParsersMap['minecraft:entity']) => rootNode)
  111:
    ((center: ParsersMap['minecraft:vec2'], spreadDistance: ParsersMap['brigadier:float'], maxRange: ParsersMap['brigadier:float'], respectTeams: ParsersMap['brigadier:bool'], targets: ParsersMap['minecraft:entity']) => rootNode)
  112:
    ((entity: ParsersMap['minecraft:entity_summon']) => returnType) &
    ((entity: ParsersMap['minecraft:entity_summon'], pos: ParsersMap['minecraft:vec3']) => returnType) &
    ((entity: ParsersMap['minecraft:entity_summon'], pos: ParsersMap['minecraft:vec3'], nbt: ParsersMap['minecraft:nbt_compound_tag']) => rootNode)
  113:
    ((team: ParsersMap['brigadier:string']) => returnType) &
    ((team: ParsersMap['brigadier:string'], displayName: ParsersMap['minecraft:component']) => rootNode)
  114:
    ((team: ParsersMap['minecraft:team']) => rootNode)
  115:
    ((team: ParsersMap['minecraft:team']) => returnType) &
    ((team: ParsersMap['minecraft:team'], members: ParsersMap['minecraft:score_holder']) => rootNode)
  116:
    ((members: ParsersMap['minecraft:score_holder']) => rootNode)
  117:
    ((value: ParsersMap['minecraft:color']) => rootNode)
  118:
    ((allowed: ParsersMap['brigadier:bool']) => rootNode)
  119:
    ((prefix: ParsersMap['minecraft:component']) => rootNode)
  120:
    ((suffix: ParsersMap['minecraft:component']) => rootNode)
  121:
    ((destination: ParsersMap['minecraft:entity']) => rootNode)
  122:
    ((location: ParsersMap['minecraft:vec3']) => rootNode)
  123:
    ((facingEntity: ParsersMap['minecraft:entity']) => returnType) &
    ((facingEntity: ParsersMap['minecraft:entity'], facingAnchor: ParsersMap['minecraft:entity_anchor']) => rootNode)
  124:
    ((facingLocation: ParsersMap['minecraft:vec3']) => rootNode)
  125:
    ((rotation: ParsersMap['minecraft:rotation']) => rootNode)
  126:
    ((targets: ParsersMap['minecraft:entity'], message: ParsersMap['minecraft:component']) => rootNode)
  127:
    ((time: ParsersMap['minecraft:time']) => rootNode)
  128:
    ((title: ParsersMap['minecraft:component']) => rootNode)
  129:
    ((fadeIn: ParsersMap['brigadier:integer'], stay: ParsersMap['brigadier:integer'], fadeOut: ParsersMap['brigadier:integer']) => rootNode)
  130:
    ((duration: ParsersMap['brigadier:integer']) => rootNode)
  131:
    ((distance: ParsersMap['brigadier:float']) => returnType) &
    ((distance: ParsersMap['brigadier:float'], time: ParsersMap['brigadier:integer']) => rootNode)
  132:
    ((pos: ParsersMap['minecraft:vec2']) => rootNode)
  133:
    ((damagePerBlock: ParsersMap['brigadier:float']) => rootNode)
  134:
    ((distance: ParsersMap['brigadier:float']) => rootNode)
  135:
    ((distance: ParsersMap['brigadier:integer']) => rootNode)
  136:
    ((time: ParsersMap['brigadier:integer']) => rootNode)
})

export type ParsersIdMap<returnType, rootNode, k extends number>  = (
  k extends keyof ParsersIdMapObject<returnType, rootNode> ?
    ParsersIdMapObject<returnType, rootNode>[k] :
    never
)
